version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing pnpm..."
      - npm install -g pnpm@8.15.0
      
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pnpm install --frozen-lockfile
      
  build:
    commands:
      - echo "Building all packages..."
      # Set placeholder DATABASE_URL for Prisma Client generation (no actual DB connection needed)
      # Override with actual DATABASE_URL in CodeBuild environment variables for production
      - export DATABASE_URL="postgresql://placeholder:placeholder@localhost:5432/placeholder"
      - pnpm build
      
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    # Include build outputs only (excludes node_modules, source files, etc.)
    - 'packages/*/dist/**/*'      # Backend and shared package builds
    - 'packages/*/build/**/*'     # Alternative build output directory
    - 'packages/*/.next/**/*'     # Next.js frontend build
    - '!packages/*/.next/cache/**/*'  # Exclude Next.js build cache
  base-directory: .

cache:
  paths:
    - 'node_modules/**/*'
    - 'packages/*/node_modules/**/*'
